services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped

    ports:
      - 80:80
    
    env_file:
      - .env
    
    depends_on:
      backend:
        condition: service_started
    
    networks: [app]

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped

    env_file:
      - .env

    expose:
      - 8080
    
    #ports:
      #-8080:8080

    depends_on:
      elastic_db:
        condition: service_healthy
      graph_db:
        condition: service_healthy
    
    networks: [app]

  elastic_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elastic
    restart: unless-stopped

    environment:
      xpack.security.enabled: "false"
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "10"
    
    #ports:
      #- 9200:9200
      #- 9300:9300
    
    volumes:
     - elastic-data:/usr/share/elasticsearch/data
    
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]   # != red
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    
    networks: [app]
  
  graph_db:
    image: neo4j:5.22
    container_name: graph
    restart: unless-stopped
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}

    #ports:
      #- 7474:7474
      #- 7687:7687
    healthcheck:
      test: ["CMD-SHELL", "wget -qo- http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

    volumes:
      - neo4j_data:/data
    
    networks: [app]
  
  admin_panel:
    build: ./admin
    container_name: admin_panel
    restart: unless-stopped
    ports:
      - 8000:8000
    
    depends_on:
      - backend
    
    networks: [app]
  
volumes:
  elastic-data:
  neo4j_data:

networks:
  app:
    driver: bridge
